# Generated by Django 6.0.3 on 2026-03-26 14:41
"""Initial migration for the simulator app."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """migrations"""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('correct_answer', models.FloatField()),
            ],
        ),
    ]
